// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ButtonWithTitle: typeof import('./src/components/buttonWithTitle.vue')['default']
    FilterPanel: typeof import('./src/components/filterPanel.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Model3d: typeof import('./src/components/model3d.vue')['default']
    MouseMenu: typeof import('./src/components/RightClickMenu.ts/mouse-menu.vue')['default']
    MPDetail: typeof import('./src/components/MPDetail.vue')['default']
    MySearch: typeof import('./src/components/mySearch.vue')['default']
    MyTable: typeof import('./src/components/myTable.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCarousel: typeof import('naive-ui')['NCarousel']
    NCarouselItem: typeof import('naive-ui')['NCarouselItem']
    NImage: typeof import('naive-ui')['NImage']
    NPopselect: typeof import('naive-ui')['NPopselect']
    Qpie: typeof import('./src/components/Qpie.vue')['default']
    ReportTable: typeof import('./src/components/reportTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SetMesPoints: typeof import('./src/components/setMesPoints.vue')['default']
    SetMesPoints2: typeof import('./src/components/setMesPoints2.vue')['default']
    SingleChart: typeof import('./src/components/singleChart.vue')['default']
    UserMenu: typeof import('./src/components/UserMenu.vue')['default']
    VuesticLogo: typeof import('./src/components/VuesticLogo.vue')['default']
    Xbar: typeof import('./src/components/Xbar.vue')['default']
    Zone: typeof import('./src/components/Zone.vue')['default']
  }
}
